[package]
authors = ["J/A <archer884@gmail.com>"]
name = "quote-rs"
version = "0.1.0"

[dependencies]
clippy = "0.0.70"
hyper = {version = "0.9.6", default-features = false}
serde = "0.7.6"
serde_json = "0.7.1"
serde_macros = "0.7.5"
url = "1.1.1"

[dev-dependencies]
dotenv = "*"