[package]
authors = ["J/A <archer884@gmail.com>"]
name = "quoters"
version = "0.1.0"

[dependencies]
clippy = "0.0.69"
hyper = {version = "0.9.6", default-features = false}
regex = "0.1.71"
serde = "0.7.5"
serde_json = "0.7.0"
serde_macros = "0.7.5"
chrono = "0.2.22"